project:
  type: website
  output-dir: docs

website:
  title: ""
  favicon: logo2.png
  navbar:
    logo: logo.jpeg
    background: "black"
    left:
      - href: sections/pbe.qmd
        text: Protótipo
      - href: sections/ucbe.qmd
        text: Conceito Urbano
      - href: "https://docs.google.com/spreadsheets/d/1lH8kZE6oc1SF1vffs-_3FoeX-rcwngIUTP1zPGSIplI/edit?usp=sharing"
        text: ✏️ Alterar

format:
  html:
    theme:
      - cyborg
    css: styles.css
    toc: true

editor: visual
