project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    logo: logo.jpeg
    background: "black" # Código hexadecimal para um tom de roxo
    left:
      - href: sections/pbe.qmd
        text: Protótipo
      - href: sections/ucbe.qmd
        text: Conceito Urbano

format:
  html:
    theme:
      - cyborg
    css: styles.css
    toc: true

editor: visual
